### ISSUE TITLE
1.0.6 does not deploy

### ISSUE THREAD

**Issue by avasseur-pivotal** [krujos/willitconnect#81]
Getting this
2016-09-09T16:39:02.14+0200 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2016-09-09T16:39:02.14+0200 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-09-09T16:39:02.14+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-09-09T16:39:02.14+0200 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-09-09T16:39:02.14+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-09-09T16:39:02.14+0200 [APP/0]      ERR 	... 31 more
2016-09-09T16:39:02.16+0200 [APP/0]      OUT Exit status 1
2016-09-09T16:39:02.17+0200 [CELL/0]     OUT Exit status 0
2016-09-09T16:39:02.27+0200 [API/0]      OUT App instance exited

1.0.5 works (though the release in github links to a file with a wrong version number 1.0.6)

**Comment by krujos** [comment]
Pulled release 1.0.6 @gambtho to post 1.0.7 shortly. 

@avasseur-pivotal thank you for the notification!!!!

**Comment by avasseur-pivotal** [comment]
Not sure what was fixed

shasum willitconnect-1.0.7.jar
6a52abf74d5b3d6c2c98f4873d6d805df40142de  willitconnect-1.0.7.jar

2016-09-09T18:01:04.66+0200 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2016-09-09T18:01:04.66+0200 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-09-09T18:01:04.66+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-09-09T18:01:04.66+0200 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-09-09T18:01:04.66+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
