### ISSUE TITLE
1.0.7 does not deploy

### ISSUE THREAD

**Issue by avasseur-pivotal** [krujos/willitconnect#86]
Not sure what was fixed #81 

shasum willitconnect-1.0.7.jar
6a52abf74d5b3d6c2c98f4873d6d805df40142de willitconnect-1.0.7.jar

2016-09-09T18:01:04.66+0200 [APP/0] ERR Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2016-09-09T18:01:04.66+0200 [APP/0] ERR at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-09-09T18:01:04.66+0200 [APP/0] ERR at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-09-09T18:01:04.66+0200 [APP/0] ERR at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-09-09T18:01:04.66+0200 [APP/0] ERR at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by gambtho** [comment]
can you provide some more info on how you're deploying?    not able to recreate the issue -- just pushed to pws - wi.cfapps.io

**Comment by avasseur-pivotal** [comment]
You are right this is very weird - as java -jar works fine but cf push fails.
I will turn on JBP DEBUG and let you know

This is on a PCF 1.7 - ERT 1.7.17

curl -L -X GET https://github.com/krujos/willitconnect/releases/download/v1.0.7/willitconnect-1.0.7.jar --output willitconnect-1.0.7.jar

shasum willitconnect-1.0.7.jar
843c7af4771c9f3a89a6631d6099d4092cc730e5  willitconnect-1.0.7.jar

cf push -p willitconnect-1.0.7.jar willitconnect -m 1G

Staging...
-----> Java Buildpack Version: v3.6 (offline) | https://github.com/cloudfoundry/java-buildpack.git#5194155

2016-09-09T18:27:54.72+0200 [CELL/0]     OUT Successfully created container
2016-09-09T18:27:54.80+0200 [CELL/0]     OUT Starting health monitoring of container
2016-09-09T18:27:54.99+0200 [CELL/0]     OUT Starting health monitoring of container
2016-09-09T18:27:55.10+0200 [APP/0]      ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2016-09-09T18:27:55.10+0200 [APP/0]      ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:422)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:401)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:392)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:261)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at willitconnect.WillItConnectApplication.main(WillItConnectApplication.java:12)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	... 8 more
2016-09-09T18:27:55.11+0200 [APP/0]      ERR Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.lang.ClassLoader.defineClass1(Native Method)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.security.AccessController.doPrivileged(Native Method)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:414)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	... 15 more
2016-09-09T18:27:55.11+0200 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-09-09T18:27:55.11+0200 [APP/0]      ERR 	... 31 more
2016-09-09T18:27:55.12+0200 [APP/0]      OUT Exit status 1
2016-09-09T18:27:55.13+0200 [CELL/0]     OUT Exit status 0
2016-09-09T18:27:55.30+0200 [APP/0]      ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:422)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:401)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:392)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:261)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at willitconnect.WillItConnectApplication.main(WillItConnectApplication.java:12)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	... 8 more
2016-09-09T18:27:55.30+0200 [APP/0]      ERR Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.ClassLoader.defineClass1(Native Method)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.security.AccessController.doPrivileged(Native Method)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:414)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	... 15 more
2016-09-09T18:27:55.30+0200 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-09-09T18:27:55.30+0200 [APP/0]      ERR 	... 31 more
2016-09-09T18:27:55.32+0200 [APP/0]      OUT Exit status 1
2016-09-09T18:27:55.33+0200 [CELL/0]     OUT Exit status 0
2016-09-09T18:27:55.43+0200 [API/0]      OUT App instance exited with guid 82cfe986-a6f0-4ee5-ab8e-5017609c826d payload: {"instance"=>"38585136-45cb-4a8a-6b67-d6a76d0d8209", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>3, "crash_timestamp"=>1473438475572695136, "version"=>"1cc1fe8a-962f-4e18-911f-6e447f766840"}

**Comment by gambtho** [comment]
can you specific the 3.8 buildpack?    curious if that/s the issue -- we're on pivotal slack if you want to chat there too

**Comment by avasseur-pivotal** [comment]
same issue on a completely other PCF 1.7 (ERT 1.7.1) with Java Buildpack Version: v3.6 (offline) | https://github.com/cloudfoundry/java-buildpack.git#5194155

**Comment by avasseur-pivotal** [comment]
Trying with JBP 3.8.1: it works
cf push -p willitconnect-1.0.7.jar willitconnect -m 1G -b https://github.com/cloudfoundry/java-buildpack.git#v3.8.1
-----> Java Buildpack Version: v3.8.1 | https://github.com/cloudfoundry/java-buildpack.git#7f47ec2
2016-09-09T18:52:52.53+0200 [CELL/0]     OUT Container became healthy

That sounds pretty serious to me that JBP 3.6 fails on this app.

**Comment by krujos** [comment]
From a WIC standpoint my preference is we just document the dependency with the releases (technically it's in the manifests & CI and we can find a way to expose it). It sounds like the JBP or spring broke backwards compatibility and i don't want to account for that in WIC. I understand that limits the usefulness / ability to update for some users (generally, ui updates) but I'm willing to make that compromise.

**Comment by gambtho** [comment]
i think that's a good plan for going forward -- i think i'll update one of the previous releases to be 3.6 compatible though too

**Comment by gambtho** [comment]
@avasseur-pivotal when you have a chance, try the -lts binary on release 1.0.7 -- works on java buildpack 3.6 for me on pws.

**Comment by avasseur-pivotal** [comment]
-lts binary works on JBP 3.6 - many thanks
